In [1]:
import numpy as np
a = np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [2]:
array = np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
array_2 = np.ones((1,5))
print(array_2)

[[1. 1. 1. 1. 1.]]


In [13]:
# Numpy.eye()
eye_array = np.eye(3) # creates a 3x3 identity matrix
print("Numpy eye array:")
print(eye_array)


Numpy eye array:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# Numpy.random.randn()
random_array = np.random.randn(3, 4) # creates a 3x4 array of random numbers from a normal distribution
print("\nNumpy random array (normal distribution):")
print(random_array)


Numpy random array (normal distribution):
[[ 1.08733222 -0.44446154 -0.75663539  1.1352426 ]
 [-0.24388759 -0.48419223 -0.80359691 -0.2208802 ]
 [ 1.51736237  1.70121138  0.07355302 -0.97198788]]


In [16]:
# Numpy.random.rand()
random_array_uniform = np.random.rand(3, 4) # creates a 3x4 array of random numbers from a uniform distribution in the range [0,1)
print("\nNumpy random array (uniform distribution):")
print(random_array_uniform)


Numpy random array (uniform distribution):
[[0.82938266 0.53349807 0.67968855 0.54444557]
 [0.50992382 0.91224172 0.73337213 0.66255704]
 [0.05269124 0.16607922 0.84188952 0.40555458]]


In [17]:
# Numpy.matrix()
mat = np.matrix([[1, 2], [3, 4]]) # creates a 2x2 matrix
print("\nNumpy matrix:")
print(mat)


Numpy matrix:
[[1 2]
 [3 4]]


In [47]:
# NumPy Array Operations
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Dot Product:")
print(np.dot(arr1, arr2))  # Dot product

print("\nTranspose:")
print(arr1.T)  # Transpose

print("\nElement-wise multiplication:")
print(np.multiply(arr1, arr2))  # Element-wise multiplication

print("\nMatrix multiplication:")
print(np.matmul(arr1, arr2))  # Matrix multiplication

print("\nElement-wise addition:")
print(np.add(arr1, arr2))  # Element-wise addition

print("\nElement-wise subtraction:")
print(np.subtract(arr1, arr2))  # Element-wise subtraction

print("\nElement-wise division:")
print(np.divide(arr1, arr2))  # Element-wise division

print("\nShape of the array:")
print(arr1.shape)  # Shape of the array

print("\nInverse of a square matrix:")
print(np.linalg.inv(arr1))  # Inverse of a square matrix

print("\nPower of a square matrix:")
print(np.linalg.matrix_power(arr1, 3))  # Power of a square matrix

print("\nNumber of elements in the array: ")
print(arr1.size)  # Number of elements in the array

Dot Product:
[[19 22]
 [43 50]]

Transpose:
[[1 3]
 [2 4]]

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]

Element-wise addition:
[[ 6  8]
 [10 12]]

Element-wise subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Shape of the array:
(2, 2)

Inverse of a square matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]

Power of a square matrix:
[[ 37  54]
 [ 81 118]]

Number of elements in the array: 
4


# PYTHON

In [50]:
import math

# Arithmetic Operations
a = 10
b = 3
print(a + b)  # Addition
print(a - b)  # Subtraction
print(a * b)  # Multiplication
print(a / b)  # Division
print(a // b) # Integer Division
print(a % b)  # Modulus
print(a ** b) # Exponentiation


13
7
30
3.3333333333333335
3
1
1000


In [51]:
a = 5

# Assignment
b = a
print("Assignment:", b)

# Addition and Assignment
a += 3
print("Addition and Assignment:", a)

# Subtraction and Assignment
a -= 3
print("Subtraction and Assignment:", a)

# Multiplication and Assignment
a *= 3
print("Multiplication and Assignment:", a)

# Division and Assignment
a /= 2
print("Division and Assignment:", a)

# Modulus and Assignment
a %= 3
print("Modulus and Assignment:", a)

# Exponentiation and Assignment
a **= 3
print("Exponentiation and Assignment:", a)


Assignment: 5
Addition and Assignment: 8
Subtraction and Assignment: 5
Multiplication and Assignment: 15
Division and Assignment: 7.5
Modulus and Assignment: 1.5
Exponentiation and Assignment: 3.375


### Comparison Operations 

In [52]:
a = 5
b = 3

# Equal to
print("Equal to:", a == b)

# Not equal to
print("Not equal to:", a != b)

# Greater than
print("Greater than:", a > b)

# Less than
print("Less than:", a < b)

# Greater than or equal to
print("Greater than or equal to:", a >= b)

# Less than or equal to
print("Less than or equal to:", a <= b)


Equal to: False
Not equal to: True
Greater than: True
Less than: False
Greater than or equal to: True
Less than or equal to: False


### Bitwise Operations

In [53]:
# Bitwise AND
a = 5  # 101
b = 3  # 011
result_and = a & b  # 001
print("Bitwise AND:", result_and)

# Bitwise OR
result_or = a | b  # 111
print("Bitwise OR:", result_or)

# Bitwise XOR
result_xor = a ^ b  # 110
print("Bitwise XOR:", result_xor)

# Bitwise NOT
result_not_a = ~a  # -(a+1)
print("Bitwise NOT of a:", result_not_a)

# Bitwise Left Shift
result_left_shift = a << 1  # 1010
print("Bitwise Left Shift:", result_left_shift)

# Bitwise Right Shift
result_right_shift = a >> 1  # 10
print("Bitwise Right Shift:", result_right_shift)


Bitwise AND: 1
Bitwise OR: 7
Bitwise XOR: 6
Bitwise NOT of a: -6
Bitwise Left Shift: 10
Bitwise Right Shift: 2


### IF - For - While

In [54]:
# if statement
num = 3
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

# for loop
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(f"I love {fruit}s")

# while loop
num = 5
factorial = 1
i = 1
while i <= num:
    factorial *= i
    i += 1
print(f"The factorial of {num} is {factorial}")


Positive number
I love apples
I love bananas
I love cherrys
The factorial of 5 is 120


### Function

In [55]:
# Function to check if a number is prime
def is_prime(num):
    """
    This function checks if a number is prime.
    """
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Function to print all prime numbers within a range
def print_primes(start, end):
    """
    This function prints all prime numbers within a specified range.
    """
    print(f"Prime numbers between {start} and {end}:")
    for num in range(start, end + 1):
        if is_prime(num):
            print(num, end=" ")
    print()

# Calling the function to print prime numbers between 1 and 20
print_primes(1, 20)


Prime numbers between 1 and 20:
2 3 5 7 11 13 17 19 


### Math

In [45]:
# Trigonometric Functions
angle = math.pi / 4
print(math.cos(angle))  # Cosine
print(math.sin(angle))  # Sine

0.7071067811865476
0.7071067811865476


In [46]:
# Other Mathematical Operations
num = 16
print(math.sqrt(num))  # Square root

4.0


Example: The code in which the elements received from the user are added to the list as many times as the number entered by the user and the average of the values in the list is calculated.

In [61]:
n = int(input("How many numbers to enter: "))
x = []
for i in range(0,n):
    elem = int(input("Enter the number: "))
    x.append(elem)
avg = sum(x) / n
print("Average of entered numbers: ", round(avg,2))

How many numbers to enter: 3
Enter the number: 24
Enter the number: 35
Enter the number: 78
Average of entered numbers:  45.67
